<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>netcoreapp3.1</TargetFramework>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\Navistar.DAO.Core\Navistar.DAO.Core.csproj" />
    <ProjectReference Include="..\Navistar.DataContext\Navistar.DataContext.csproj" />
    <ProjectReference Include="..\Navistar.Model.common\Navistar.Model.common.csproj" />
    <ProjectReference Include="..\Navistar.Model.Request\Navistar.Model.Request.csproj" />
    <ProjectReference Include="..\Navistar.Model.Response\Navistar.Model.Response.csproj" />
    <ProjectReference Include="..\Navistar.Utils.Core\Navistar.Utils.Core.csproj" />
  </ItemGroup>

</Project>
